kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-porch-system-porch-server
groups:
- system:cluster-admins
- system:nodes
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:porch-system:porch-server
