kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-admin-metallb-system-controller
allowPrivilegeEscalation: false
groups:
- system:cluster-admins
- system:nodes
fsGroup:
  type: MustRunAs
  ranges:
    - min: 65534
      max: 65534
readOnlyRootFilesystem: true
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAsNonRoot
  uid: 65534
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:metallb-system:controller
