kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
allowPrivilegeEscalation: false
readOnlyRootFilesystem: true
metadata:
  name: scc-resource-group-system-resource-group-sa
groups:
- system:cluster-admins
- system:nodes
runAsUser:
  type: MustRunAsNonRoot
  uid: 1000
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:resource-group-system:resource-group-sa
