apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-flux-src-kustomization
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: flux-gitrepo-kust
    repo: catalog-nephio-optional
    revision: main
  downstream:
    package: example-flux-gr-kust
    repo: mgmt
  injectors:
  - kind: WorkloadCluster
    name: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
