apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oai-du
spec:
  upstream:
    repo: catalog-workloads-oai
    package: pkg-example-du-bp
    revision: main
  downstream:
    repo: edge
    package: oai-ran-du
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge
